### ISSUE TITLE
Is there any plan to add wayland support for screego?

### ISSUE THREAD

**Issue by jbrown8380** [screego/server#171]
I've learned that if I log into my Rocky 8 machine using wayland as my window manager, I can't share my screen in screego.

On the other hand, if I login and specifically choose classic X11 as my window manager, then screen sharing works just fine.  This is an easy enough workaround, but I was just wondering if wayland support was in the development path.

**Comment by jmattheis** [comment]
You need to properly configure your system to share your screen with wayland. This is more complicated because of the additional access restrictions in wayland. Screego doesn't interact with X11, wayland or anything like that. It only interacts with browser APIs.

See here https://wiki.archlinux.org/title/PipeWire#WebRTC_screen_sharing

**Comment by jbrown8380** [comment]
Clearly sounds like this is not a screego issue.  @jmattheis, thank you for your response.  Closing issue.
