### ISSUE TITLE
https://app.screego.net/ Secure?

### ISSUE THREAD

**Issue by AdelleBernal** [screego/server#178]
I am a tech non-savvy :) Is it secure to use this for seminars? What about privacy, etc?
I want to use the https://app.screego.net/ directly.

Thanks!

**Comment by jmattheis** [comment]
Hey @AdelleBernal, if you use Screego you basically have to trust the server owner to not do anything malicious. It is technically possible to intercept the video stream and get a copy of it, but this functionality doesn't exist inside Screego. This risk is similar for services like Google Hangouts, etc.

I'm not doing anything malicious with https://app.screego.net/, but you basically have to trust me there; there isn't really a way for me to prove or guarantee this. If it's something security-critical, then it's possible and recommended to self-host Screego.

As a side note: Screego isn't optimized for seminars, because the presenter uploads the video stream to **every** viewer. This requires a lot of bandwidth and computational power, because the video stream has to be encoded and encrypted.

**Comment by AdelleBernal** [comment]
Thanks for the clarification. Would it be hard to set up a self-host Screego for a non-programmer like me?

**Comment by jmattheis** [comment]
To set up Screego on your own, you don't necessarily have to be a programmer. You would need to expose Screego to the other users you want to share to. This either means renting a server that is accessible from the internet, or exposing a local computer to the internet (this would require configuration on your router).

Additionally, you need a certificate for securing the connection with https/tls, this is free via https://letsencrypt.org/en/, but it requires setup. The last step would be to actually install Screego, there are docs https://screego.net/#/install, but they require some knowledge in servers.
