### ISSUE TITLE
Feature Request: Audio

### ISSUE THREAD

**Issue by dannykorpan** [screego/server#22]
It would be great if it's possible to also stream  the audio of the desktop e.g. from applications, presentations etc.

**Comment by alectrocute** [comment]
As per the `getUserMedia`/`getDisplayMedia` webRTC spec, system audio would only be supported on Windows & ChromeOS with no expected support for macOS nor Linux. Screengo would need to become an Electron app and utilize its own loopback audio driver (or `pulseaudio`) for cross-platform support.

**Comment by jmattheis** [comment]
Yeah, this is currently out of scope, Screego should stay as simple as possible.

**Comment by ThelloD** [comment]
Imo, no audio support is a major drawback compared to way more simplistic solutions. In my opinion, it wouldn't be that bad if sharing audio would not work on all browsers/platforms. Quickly showing a video with audio is simply not possible with Screego. Of course it's not great if certain platforms lack features, but it's way worse if such an important feature is not available on **any** platform.

**Comment by L11R** [comment]
@ThelloD I added audio sharing in my fork: https://github.com/L11R/screego
Should work.

**Comment by ThelloD** [comment]
@L11R Many hanks! :)
Unfortunately didn’t had the time to try it out, yet, but will give it a try for sure. 

Did you consider creating a pull request? It seems you had to change [only a couple of lines](https://github.com/L11R/screego/commit/326d3115e431e7bb1118cb5c9c83a381d2ce6f0f) in order to get it working. Maybe there’s still a chance that it will be merged by @jmattheis?

**Comment by L11R** [comment]
@ThelloD it is draft improvement. I am not a frontend developer, did it almost blindly, possibly has bugs.
