### ISSUE TITLE
get black screen and no audio on iPhone iOS 14.2

### ISSUE THREAD

**Issue by inglesuniversal** [screego/server#55]
Any clues?

**Comment by jmattheis** [comment]
Have you followed the steps on https://screego.net/#/faq?id=stream-doesnt-load ?

**Comment by ThelloD** [comment]
I have the same issue on my iPhone. However, as soon as a second stream starts and clicking on the preview of the second stream, suddenly both a preview is shown for both streams and playback controls are shown. Unfortunately iOS seems to have troubles with simultaneous playback of multiple video streams. In order to start playback of a stream, the user has to click on the preview.
Therefore, I assume, that the first stream is just not started because of a missing auto-play or similar event.

**Comment by jmattheis** [comment]
Closing this issue, as screego's main use-case is desktop sharing.
